# Comment that will be sent if an issue is judged to be closed
comment: "Hi there.  Thank you for filing this issue.  Unfortunately, we cannot help you, because the required information is missing.  Please open a new issue, using the template to provide all information."
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: bug report
  - "Describe the bug"
  - "Steps to reproduce the behavior"
  - "Expected behavior"
  - "Screenshots"
  - "Environment"
  - "deCONZ Logs"
  - "Additional context"
- content:
# Example 2: Device Request
  - "Device"
  - "Screenshots"
- content:
# Example 3: Feature Request
  - "Feature request type"
  - "Description"
  - "Considered alternatives"
  - "Additional context"
- content:
# Example 4: User Question
  - "Describe the question or issue you are having"
  - "Screenshots"
  - "Environment"
  - "deCONZ Logs"
  - "Additional context"
# The issue is judged to be legal if it includes all keywords from any of these configs.
# Or it will be closed by the app.
