name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'Feature Request'
      - 'Enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'Fix'
      - 'bugfix'
      - 'bug'
  - title: 'Devices'
    labels:
    - 'Device Request'
    - 'Device Improvement'

change-template: |
  * $TITLE @$AUTHOR (#$NUMBER)

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor' 
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # Contributors:
  The following users have been contributing to this release. Thank you for that! <br/>
  $CONTRIBUTORS	<br/>
  # Changes
  $CHANGES
