name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'New devices'
    label: 'device-request'

change-template: '**$TITLE @$AUTHOR (#$NUMBER):**   <br/> $BODY<br/>'

  

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor' 
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # Changes

  $CHANGES
